from pathlib import Path

from butterfly.corpus.skills import BUILDERS
from butterfly.corpus.skills.common import contains_mojibake


def test_corpus_skill_sources_have_no_mojibake_markers():
    root = Path(__file__).resolve().parents[1] / "butterfly" / "corpus" / "skills"
    bad = []
    for path in sorted(root.glob("*.py")):
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if contains_mojibake(line):
                bad.append(f"{path.name}:{lineno}: {line.strip()}")
    assert not bad, "Mojibake in corpus source:\n" + "\n".join(bad)


def test_all_corpus_builders_generate_clean_unicode():
    bad = []
    for index, (name, builder) in enumerate(sorted(BUILDERS.items())):
        train, valid = builder(910000 + index)
        for split, rows in (("train", train), ("valid", valid)):
            for row_index, row in enumerate(rows):
                user = str(row.get("user", ""))
                assistant = str(row.get("assistant", ""))
                if contains_mojibake(user) or contains_mojibake(assistant):
                    bad.append(f"{name}/{split}/{row_index}: user={user!r} assistant={assistant!r}")
                    if len(bad) >= 20:
                        break
            if len(bad) >= 20:
                break
        if len(bad) >= 20:
            break
    assert not bad, "Mojibake generated by corpus builders:\n" + "\n".join(bad)
