from __future__ import annotations

import json
import shutil
import time

from .config import (
    ROOT,
    LEGACY_TOKENIZER_PATH,
    TOKENIZERS_DIR,
    BENCHMARKS_DIR,
    ensure_dirs,
)
from .registry import (
    get_active_entry,
    update_entry,
    promote,
    compact_to_active,
    load_registry,
    save_registry,
    append_history,
)
from .checkpoint import (
    load_entry,
    load_checkpoint,
    save_stable_model,
    move_model_artifacts,
    delete_model_artifacts,
)
from .trainer import best_device
from .learning.evaluator import (
    BENCHMARK_SUITE_VERSION,
    behavior_benchmark,
    print_benchmark,
    save_benchmark,
)


def _compact_legacy_active_checkpoint(entry):
    """Strip legacy Adam state without changing neural weights."""
    from .config import MODELS_DIR

    old = MODELS_DIR / entry["path"]
    if old.suffix != ".pt" or not old.exists():
        return entry

    version = entry["version"]
    lean = MODELS_DIR / f"butterfly-v{version}.safetensors"
    print(f"Compacting legacy v{version} checkpoint...")
    print(f"Legacy checkpoint: {old.stat().st_size/1024/1024:.1f} MB")

    model, payload, _ = load_entry(entry, device="cpu")
    save_stable_model(
        lean,
        model,
        extra={
            "version": version,
            "storage_migration": "legacy-pt-to-safetensors",
            "optimizer_removed": "optimizer" in payload,
            "legacy_extra": payload.get("extra") or {},
        },
    )

    verify_model, _ = load_checkpoint(lean, device="cpu")
    original = model.state_dict()
    restored = verify_model.state_dict()
    if original.keys() != restored.keys() or any(
        not original[key].equal(restored[key]) for key in original
    ):
        delete_model_artifacts(lean)
        raise RuntimeError(
            "Legacy checkpoint compaction verification failed. Original .pt was NOT deleted."
        )

    update_entry(
        version,
        path=lean.name,
        metadata={
            "storage_format": "safetensors-weights-only",
            "optimizer_included": False,
            "compacted_from": old.name,
        },
    )
    old.unlink(missing_ok=True)
    print(f"Verified lean checkpoint: {lean.stat().st_size/1024/1024:.1f} MB")
    print("Legacy .pt removed only after exact weight verification.")
    return get_active_entry()


def prepare_v0004():
    """Kept for compatibility with the already-completed v0.0004 pipeline."""
    ensure_dirs()
    entry = get_active_entry()
    if not entry:
        raise RuntimeError("No hay Butterfly activa.")

    version = entry["version"]
    meta = entry.get("metadata") or {}
    if not meta.get("tokenizer_path"):
        if not LEGACY_TOKENIZER_PATH.exists():
            raise FileNotFoundError(LEGACY_TOKENIZER_PATH)
        snap = TOKENIZERS_DIR / f"tokenizer-v2-v{version}.json"
        shutil.copy2(LEGACY_TOKENIZER_PATH, snap)
        update_entry(version, metadata={"tokenizer_path": str(snap.relative_to(ROOT))})
        entry = get_active_entry()
        print(f"Old tokenizer preserved as {snap}")

    # This old filename is kept only for backward compatibility. New evaluations
    # use the explicit suite-v0.00041 filenames generated by `butterfly evaluate`.
    bench = BENCHMARKS_DIR / f"baseline-v{version}-v0004-suite.json"
    if bench.exists():
        print(f"Legacy v0.0004 baseline already exists: {bench}")
        metrics = json.loads(bench.read_text(encoding="utf-8"))
        _compact_legacy_active_checkpoint(get_active_entry())
        return metrics

    print("Legacy prepare step is no longer needed after v0.0004 promotion.")
    _compact_legacy_active_checkpoint(get_active_entry())
    return None


def _remove_registry_version(version: str):
    reg = load_registry()
    reg["versions"] = [x for x in reg.get("versions", []) if x["version"] != version]
    save_registry(reg)


def _resolve_candidate(candidate_version: str | None):
    reg = load_registry()
    active_version = reg.get("active")
    rows = reg.get("versions", [])

    if candidate_version:
        candidate = next((x for x in rows if x.get("version") == candidate_version), None)
        if not candidate:
            raise RuntimeError(f"Candidate v{candidate_version} is not registered.")
        if candidate.get("version") == active_version or candidate.get("status") == "active":
            raise RuntimeError(
                f"Safety stop: v{candidate_version} is already the ACTIVE brain. "
                "An active brain can never be treated as a rejectable candidate."
            )
        if candidate.get("status") != "candidate":
            raise RuntimeError(
                f"v{candidate_version} has status {candidate.get('status')!r}, not 'candidate'."
            )
        return candidate

    candidates = [
        x
        for x in rows
        if x.get("status") == "candidate" and x.get("version") != active_version
    ]
    if not candidates:
        return None
    if len(candidates) > 1:
        versions = ", ".join(x.get("version", "?") for x in candidates)
        raise RuntimeError(
            f"More than one candidate is registered ({versions}). "
            "Run compare-promote --candidate VERSION."
        )
    return candidates[0]


def _strict_baseline(active):
    path = BENCHMARKS_DIR / (
        f"baseline-v{active['version']}-suite-v{BENCHMARK_SUITE_VERSION}.json"
    )
    if path.exists():
        value = json.loads(path.read_text(encoding="utf-8"))
        if value.get("suite_version") == BENCHMARK_SUITE_VERSION:
            return value, path

    print(
        f"No strict v{BENCHMARK_SUITE_VERSION} baseline for active v{active['version']}; "
        "evaluating it now..."
    )
    model, _, tok = load_entry(active, device=best_device())
    metrics = behavior_benchmark(model, tok)
    save_benchmark(path, metrics)
    return metrics, path


def compare_and_promote(candidate_version: str | None = None):
    """Compare active vs candidate with semantics-first hard gates.

    v0.00041 safety rule: the active model is NEVER deletable by this function.
    A candidate must be a distinct registry entry whose status is exactly
    `candidate`.
    """
    active = get_active_entry()
    if not active:
        raise RuntimeError("No active baseline model.")

    candidate = _resolve_candidate(candidate_version)
    if candidate is None:
        print("No candidate brain is registered. Nothing to compare or delete.")
        print(f"Active brain remains Butterfly v{active['version']}.")
        return False

    candidate_version = candidate["version"]
    meta = candidate.get("metadata") or {}
    seed_brain = meta.get("seed_brain")
    if seed_brain is not None and seed_brain != active["version"]:
        raise RuntimeError(
            f"Safety stop: v{candidate_version} lineage says seed={seed_brain!r}, "
            f"but active baseline is v{active['version']}. Nothing was promoted or deleted."
        )
    candidate_tokenizer = meta.get("tokenizer_path")
    active_tokenizer = (active.get("metadata") or {}).get("tokenizer_path")
    if candidate_tokenizer is not None and candidate_tokenizer != active_tokenizer:
        raise RuntimeError(
            f"Safety stop: v{candidate_version} must inherit the exact accepted tokenizer. "
            "Tokenizer lineage differs; nothing was promoted or deleted."
        )
    if candidate_version == active["version"]:
        # Defensive duplicate guard even though _resolve_candidate already checks.
        raise RuntimeError("Safety stop: candidate and active versions are identical.")

    baseline, baseline_path = _strict_baseline(active)

    print(f"\nEvaluating candidate v{candidate_version} with suite v{BENCHMARK_SUITE_VERSION}...")
    cm, _, ct = load_entry(candidate, device=best_device())
    cand = behavior_benchmark(cm, ct)
    print_benchmark(cand)

    report = {
        "suite_version": BENCHMARK_SUITE_VERSION,
        "baseline_version": active["version"],
        "candidate_version": candidate_version,
        "baseline": baseline,
        "candidate": cand,
        "created_at": time.time(),
    }
    report_path = BENCHMARKS_DIR / (
        f"comparison-v{active['version']}-vs-v{candidate_version}"
        f"-suite-v{BENCHMARK_SUITE_VERSION}.json"
    )
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    improvement = cand["score"] - baseline["score"]
    no_major_regression = (
        cand["conversation_component"] >= baseline.get("conversation_component", 0.0) - 0.02
        and cand["comprehension_component"] >= baseline.get("comprehension_component", 0.0) - 0.02
        and cand["instruction_component"] >= baseline.get("instruction_component", 0.0) - 0.02
        and cand["epistemic_dialogue_component"]
        >= baseline.get("epistemic_dialogue_component", 0.0) - 0.02
    )
    passes = (
        improvement >= 0.03
        and bool(cand.get("promotion_eligible"))
        and no_major_regression
    )

    print(f"\nBaseline overall : {baseline['score']:.4f}")
    print(f"Candidate overall: {cand['score']:.4f}")
    print(f"Improvement      : {improvement:+.4f}")
    print(f"Hard gates       : {'PASS' if cand.get('promotion_eligible') else 'FAIL'}")
    print(f"No regressions   : {'PASS' if no_major_regression else 'FAIL'}")

    from .config import MODELS_DIR, DATA_DIR

    candidate_path = MODELS_DIR / candidate["path"]
    active_path = MODELS_DIR / active["path"]
    if candidate_path.resolve() == active_path.resolve():
        raise RuntimeError(
            "Safety stop: candidate path resolves to the active model path. Nothing was deleted."
        )

    if passes:
        canonical = MODELS_DIR / f"butterfly-v{candidate_version}.safetensors"
        if candidate_path.resolve() != canonical.resolve():
            move_model_artifacts(candidate_path, canonical)
            update_entry(candidate_version, path=canonical.name)

        update_entry(
            candidate_version,
            score=cand["score"],
            metadata={
                "benchmark": str(report_path.relative_to(ROOT)),
                "benchmark_suite": BENCHMARK_SUITE_VERSION,
                "storage_format": "safetensors-weights-only",
                "optimizer_included": False,
            },
        )
        promote(candidate_version)
        append_history(
            candidate_version,
            "promoted",
            score=cand["score"],
            metadata={
                "parameters": (candidate.get("metadata") or {}).get("parameters"),
                "tokenizer_vocab": (candidate.get("metadata") or {}).get("tokenizer_vocab"),
                "benchmark": str(report_path.relative_to(ROOT)),
                "benchmark_suite": BENCHMARK_SUITE_VERSION,
                "brain_format": "safetensors-weights-only",
            },
        )
        compact_to_active()
        LEGACY_TOKENIZER_PATH.unlink(missing_ok=True)
        for duplicate in (
            DATA_DIR / "consolidated.txt",
            DATA_DIR / "distilled.txt",
            DATA_DIR / "distilled.jsonl",
        ):
            duplicate.unlink(missing_ok=True)

        print(f"\nPROMOTED Butterfly v{candidate_version}.")
        print("The accepted brain passed BOTH score improvement and strict semantic hard gates.")
        print("Old physical brain/tokenizer are burned only after successful promotion.")
        print("Corpus, memory, verified knowledge, lessons and benchmarks remain.")
        return True

    print("\nREJECTED: candidate failed the current strict promotion policy.")
    if improvement < 0.03:
        print("  - Overall improvement is below +0.0300.")
    if not cand.get("promotion_eligible"):
        for reason in cand.get("promotion_blockers", []):
            print(f"  - {reason}")
    if not no_major_regression:
        print("  - At least one major capability regressed by more than 0.02.")

    append_history(
        candidate_version,
        "rejected",
        score=cand.get("score"),
        metadata={
            "benchmark": str(report_path.relative_to(ROOT)),
            "benchmark_suite": BENCHMARK_SUITE_VERSION,
            "critical_failures": cand.get("critical_failures", []),
        },
    )
    delete_model_artifacts(candidate_path)
    _remove_registry_version(candidate_version)
    print("Candidate brain deleted; corpus, tokenizer assets, memory and report were kept.")
    return False


def prepare_v0005():
    """Safety/preflight for the v0.0005 continued-learning generation."""
    ensure_dirs()
    active = get_active_entry()
    if not active:
        raise RuntimeError("No active Butterfly brain.")

    if active["version"] == "0.0005":
        print("Butterfly v0.0005 is already active. Preparation is already complete.")
        return True
    if active["version"] != "0.0004":
        raise RuntimeError(
            f"Expected accepted brain v0.0004 before v0.0005 training, but active is v{active['version']}. "
            "Nothing was changed."
        )

    model, payload, tokenizer = load_entry(active, device="cpu")
    tokenizer_rel = (active.get("metadata") or {}).get("tokenizer_path")
    if not tokenizer_rel:
        raise RuntimeError("Active v0.0004 has no tokenizer path in registry metadata.")
    tokenizer_path = ROOT / tokenizer_rel
    if not tokenizer_path.exists():
        raise FileNotFoundError(tokenizer_path)
    if model.cfg.vocab_size != tokenizer.vocab_size:
        raise RuntimeError("Active model/tokenizer vocabulary mismatch. Nothing was changed.")

    baseline, baseline_path = _strict_baseline(active)
    print("ButterflyAI v0.0005 preflight OK.")
    print(f"Active seed brain      : v{active['version']} (READ ONLY until promotion)")
    print(f"Parameters             : {model.parameter_count():,}")
    print(f"Tokenizer              : {tokenizer_path}")
    print(f"Tokenizer vocab        : {tokenizer.vocab_size:,}")
    print(f"Strict baseline suite  : v{BENCHMARK_SUITE_VERSION}")
    print(f"Strict baseline score  : {baseline.get('score', 0.0):.4f}")
    print(f"Critical pass rate     : {baseline.get('critical_pass_rate', 0.0):.4f}")
    print(f"Baseline file          : {baseline_path}")
    print("v0.0005 will inherit these exact weights and tokenizer; it does NOT restart from random weights.")
    print("Memory, corpus, verified knowledge, history and benchmarks are preserved.")
    return True



def prepare_v00051():
    """Preflight for v0.00051 + benchmark-suite v0.00042.

    v0.0005 was a rejected experiment, so the accepted seed remains v0.0004.
    This step does not train or modify weights. It freezes a new, harder baseline
    using punctuationless/casual/contrastive benchmark cases.
    """
    ensure_dirs()
    active = get_active_entry()
    if not active:
        raise RuntimeError("No active Butterfly brain.")

    if active["version"] == "0.00051":
        print("Butterfly v0.00051 is already active. Preparation is already complete.")
        return True
    if active["version"] != "0.0004":
        raise RuntimeError(
            f"v0.00051 expects accepted seed v0.0004 after rejected v0.0005, but active is v{active['version']}. "
            "Nothing was changed. Inspect STATUS before continuing."
        )

    stale_v5 = next(
        (x for x in load_registry().get("versions", []) if x.get("version") == "0.0005" and x.get("status") == "candidate"),
        None,
    )
    if stale_v5:
        raise RuntimeError(
            "A v0.0005 candidate is still registered. Do not stack experiments. "
            "Run the normal v0.0005 compare/reject flow first."
        )

    model, _, tokenizer = load_entry(active, device="cpu")
    tokenizer_rel = (active.get("metadata") or {}).get("tokenizer_path")
    if not tokenizer_rel:
        raise RuntimeError("Active v0.0004 has no tokenizer lineage.")
    tokenizer_path = ROOT / tokenizer_rel
    if not tokenizer_path.exists():
        raise FileNotFoundError(tokenizer_path)
    if model.cfg.vocab_size != tokenizer.vocab_size:
        raise RuntimeError("Active model/tokenizer vocabulary mismatch. Nothing was changed.")

    baseline, baseline_path = _strict_baseline(active)
    old_path = BENCHMARKS_DIR / "baseline-v0.0004-suite-v0.00041.json"
    old_score = None
    if old_path.exists():
        try:
            old_score = json.loads(old_path.read_text(encoding="utf-8")).get("score")
        except Exception:
            old_score = None

    print("ButterflyAI v0.00051 preflight OK.")
    print(f"Active seed brain      : v{active['version']} (READ ONLY until promotion)")
    print(f"Parameters             : {model.parameter_count():,}")
    print(f"Tokenizer              : {tokenizer_path}")
    print(f"Tokenizer vocab        : {tokenizer.vocab_size:,}")
    print(f"New strict suite       : v{BENCHMARK_SUITE_VERSION}")
    print(f"v0.00042 baseline score: {baseline.get('score', 0.0):.4f}")
    print(f"Critical pass rate     : {baseline.get('critical_pass_rate', 0.0):.4f}")
    print(f"Robustness component   : {baseline.get('robustness_component', 0.0):.4f}")
    print(f"Contrastive component  : {baseline.get('contrastive_component', 0.0):.4f}")
    if old_score is not None:
        print(f"Previous v0.00041 score: {float(old_score):.4f} (kept for history; not directly comparable)")
    print(f"Baseline file          : {baseline_path}")
    print("No weights, tokenizer, memory or old benchmark were modified.")
    print("v0.00051 will continue from v0.0004 and must beat THIS harder baseline plus all hard gates.")
    return True
